[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://wi-production-ae1c.up.railway.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws/*"
  to = "https://wi-production-ae1c.up.railway.app/ws/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200